services:
  db:
    image: mysql:lastest
    restart: always
    enviroment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - \Users\NoteLenovo\Desktop\Rocketseat\mysql:\var\lib\mysql